### ISSUE TITLE
Update SMASolarMQTT

### ISSUE THREAD

**Issue by FutureCow** [stuartpittaway/SMASolarMQTT#1]
Hello Stuart,

Is it possible to update this repo. I'm not using Emon, but i want to get the SMA values inside MQTT. I see there are quite some update over here:
https://github.com/openenergymonitor/emonhub/commits/emon-pi/src/interfacers/EmonHubSMASolarInterfacer.py

But i can't use it directly for just getting the values to my MQTT Broker.

Thanks

**Comment by stuartpittaway** [comment]
Hello, this code is very old now the version you mention on emon hub works better but isn't directly suitable for MQTT without a lot of work.
